"""Shared MedClear runtime configuration."""

from skill.constants import (  # backward compatible source of truth
    DEFAULT_MISTRAL_MODEL,
    MAX_PRIMARY_DIAGNOSIS_LENGTH,
    MAX_RAW_CLINICAL_NOTES_LENGTH,
    MAX_REQUEST_BODY_BYTES,
    MAX_REQUESTED_SERVICE_LENGTH,
    MAX_UPLOAD_FILE_SIZE,
    MISTRAL_MAX_OUTPUT_TOKENS,
    MISTRAL_MODEL_CANDIDATES,
)

__all__ = [
    "DEFAULT_MISTRAL_MODEL",
    "MAX_PRIMARY_DIAGNOSIS_LENGTH",
    "MAX_RAW_CLINICAL_NOTES_LENGTH",
    "MAX_REQUEST_BODY_BYTES",
    "MAX_REQUESTED_SERVICE_LENGTH",
    "MAX_UPLOAD_FILE_SIZE",
    "MISTRAL_MAX_OUTPUT_TOKENS",
    "MISTRAL_MODEL_CANDIDATES",
]
