export {
  BASE,
  fetchCaseById,
  fetchComplexCaseInput,
  fetchHealth,
  fetchInputSchema,
  fetchTrainingCases,
  generateAppealDraft,
  reviewCase as analyzeCase,
  reviewCase,
  runValidation,
  runValidationStream,
  uploadAndReview as uploadAndAnalyze,
  uploadAndReview,
} from '@/services/apiClient'
